Vagrant.configure("2") do |config|
  servers=[
      # {
      #   :hostname => "Worker1",
      #   :box => "bento/ubuntu-22.04-arm64",
      #   :ip => "172.16.1.50",
      #   :ssh_port => '2200'
      # },
      {
        :hostname => "Worker2",
        :box => "bento/ubuntu-22.04-arm64",
        :ip => "172.16.1.51",
        :ssh_port => '2201'
      },
      {
        :hostname => "Manager1",
        :box => "bento/ubuntu-22.04-arm64",
        :ip => "172.16.1.52",
        :ssh_port => '2202'
      }
    ]

  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network :private_network, ip: machine[:ip]
          node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
          # node.vm.synced_folder "../data", "/home/vagrant/data"
          node.vm.provision "file", source: "./docker-installation.sh", destination: "/home/vagrant/docker-installation.sh"
          if node.vm.hostname == "Manager1"
            node.vm.provision "file", source: "./docker-swarm.sh", destination: "/home/vagrant/docker-swarm.sh"
          end
          # node.vm.provision "file", source: "./docker-compose.sh", destination: "/home/vagrant/docker-compose.sh"
          node.vm.provision "shell", inline: "/home/vagrant/docker-installation.sh"
          config.vm.provider "parallels" do |prl|
            prl.memory = 1024
            prl.cpus = 1
          end
      end
  end
end